### PR TITLE
Modularized the response configuration

### PR DESCRIPTION
**Pull request by AndrewJR350**
- modularized the response configuration

- changed var to const

- formatted the code to follow camalCase naming conversion

- used arrow functions

### CODE REVIEW

**Comment by AndrewJR350** [comment]
Yes because I standardized the return format 
(Like AWS Lambda)
Since front end also changing I thought it's good to follow it like this 
But if it's needed you cab switch back to normal one by removing status in return module

**Comment by psnmissaka** [comment]
Good job!

**Comment by psnmissaka** [comment]
@AndrewJR350 as @bhavyaagg has noticed it breaks the current front-end. I don't think you have to do a lot changes. Fix them and update the PR

**Comment by psnmissaka** [comment]
Good job @AndrewJR350

**Comment by shivamarora96** [comment]
@AndrewJR350 Nice job :+1:

**Comment by shivamarora96** [comment]
@AndrewJR350 @psnmissaka  Should we need to validate output from DB as well?  For eg: while hitting getAllPosts ( or any other get Request ) if data (array) from DB is null (length = 0) then we should show some result message. Should we need this?

**Pull request merged**
