### PR TITLE
UI improvements

### LINKED ISSUE #143: UI Discrepancies
## Type of issue:
- [x] Bug / Error
- [ ] Idea / Feature
- [x] Improvement detail

## Short description on the issue

- The **Profile** and **Logout** tabs on the nav-bar are aligned one below the other, they should appear beside each other.

- The **Issue** field is not getting cleared on clicking the `Clear` button (while creating a post).

- The image alignment in the nav-bar (the avatar image beside profile button) and in the stack images on the side-nav is broken, the image should appear in line with the identifiers.

- The **Common Feed** text on the feed page overflows out of view and wraps under the side-nav. The alignment needs to be fixed.

- The profile image of the user on the profile image would look better with a radius and a boundary around it.

- **Developed by SCoRE** is not visible because it is wrapped under the side-nav. It should preferably appear over the side-nav, at the very bottom.

- The picture beside the **Profile** tab should be the Github avatar of the user rather than a random picture.

## Possible fix
The corresponding PR fixes the issue

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
fixes #143

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
## Screenshots 

screen shot 2018-08-23 at 10 06 16 pm

screen shot 2018-08-25 at 3 18 28 pm

screen shot 2018-08-25 at 3 18 56 pm

**Comment by VibhorCodecianGupta** [comment]
@psnmissaka fixed conflicts

**Comment by VibhorCodecianGupta** [comment]
@psnmissaka @agentmilindu fixed conflicts. If this PR turns out to be fine, I'd like to propose a revamp for the a better UI throughout :)

**Comment by psnmissaka** [comment]
@VibhorCodecianGupta the `developed by Score`  section doesn't seem to be on the bottom. However I will merge the PR for now. We would very much welcome such a proposals of course if you are interested

**Comment by VibhorCodecianGupta** [comment]
@psnmissaka `developed by Score` was added in a row class after the row class which contains all the main content of the page. Now, since the left nav has a vertical height of 100%, it flows down all the way to end of the page. The `developed by Score`, therefore, was hiding behind the side nav and hence not visible. One way was to align it to the bottom right, but I took the liberty of trying out the scenic way and added the `made with <3 by Score` foot note ONTO the side nav. So now it is both visible, and not on the next row class.
Do let me know if that works or not, will be happy to change.

**Pull request merged**
