### PR TITLE
Fix Warning  Issue #97 #99 #100

### PR DESCRIPTION
**Pull request by shivamarora96**
Fix warning for mongoose connection

### CODE REVIEW

**Comment by shivamarora96** [comment]
@psnmissaka  kindly check out this pr

**Comment by shivamarora96** [comment]
@psnmissaka  ki dly check out this pr

**Comment by psnmissaka** [comment]
issue #99 and #100 are fixed in a previous PR. Make sure that when you create an issue or take up on a task, it is not done before. And when you create a PR make sure it only contains work related to one particular issue. 
Update this PR with only the fix to #97

**Comment by shivamarora96** [comment]
@psnmissaka kindly check #99 again. I am not talking about statuscodes.

**Comment by shivamarora96** [comment]
@psnmissaka  #100 is still unfixed. In routes.js file every res is using send () instead of which res.JSON() should be used.

**Comment by psnmissaka** [comment]
They are fixed on open PRs that are on hold

**Pull request closed without merging**
