### PR TITLE
Fix codacy

### PR DESCRIPTION
**Pull request by bhavyaagg**
@agentmilindu @psnmissaka I have created this PR to fix the codacy issues. I did some research on codacy and found that we can make codacy behave in a way using the .eslintrc.js config file. I have created a config file and reformatted files to follow the same. There are still some issues which will be solved as we reformat other files or add rules for it in the config file.

### CODE REVIEW

**Comment by bhavyaagg** [comment]
Resolved the Merge conflicts.

**Comment by bhavyaagg** [comment]
@psnmissaka @agentmilindu @padamchopra Can we merge this?

**Comment by padamchopra** [comment]
@bhavyaagg Just so you know, I actually don't have the merging rights :sweat_smile: I'm the grand prize winner for Score this GCI and contributed to Stackle and Bassa, so that's why I review them. I can only provide additional reviews and not merge the PRs :grimacing:

**Comment by bhavyaagg** [comment]
@padamchopra Understood man. Congratulations for winning the GCI. I was a GCI mentor this time with JBoss Community. And nevertheless thank you for reviewing the PRs :)

**Comment by bhavyaagg** [comment]
@psnmissaka @agentmilindu API was not changed in this PR so endpoints will work perfectly.

**Comment by psnmissaka** [comment]
Please update the PR removing the conflicts.

**Pull request closed without merging**
