### PR TITLE
Links hidden upon page refresh when a session is active - issue fixed

### PR DESCRIPTION
**Pull request by ntbandara3**
Implementation changed to check if the user is logged in upon page refresh.

### CODE REVIEW

**Comment by agentmilindu** [comment]
@tharindupr @psnmissaka @padamchopra Please review!

**Comment by agentmilindu** [comment]
@ntbandara3 It is good if you can describe what you did in the PR's description. Some screenshots before and after the fix would be awesome!

**Comment by ntbandara3** [comment]
@agentmilindu Sure, I'll add them.

**Comment by padamchopra** [comment]
@ntbandara3 In line 22- `vm.isAuthenticated = isLoggedIn();` of file `stackle_app/app/scripts/directives/toolbar.directive.js`, the isLoggedIn() function is used before it has been defined, can you move the declaration before this to make the PR pass the Codacy tests as well ✨

**Comment by ntbandara3** [comment]
@padamchopra Done :+1: :smile:

**Comment by agentmilindu** [comment]
@psnmissaka @tharindupr Can we merge this PR?

**Pull request merged**
